### ISSUE TITLE
Missing CS 492 Hall of Fame - Winter 2023

### ISSUE THREAD

**Issue by ElijahCirioli** [robwhess/my-osu-website#29]
Given that there is no license in this repository specifying otherwise, I am inclined to believe that it comes _with_ warranty. Under such warranty I believe we as students are entitled to security updates, including my emotional security. I want to show other people the hall of fame for the CS 492 class that I took in Winter of 2023 so that I can act surprised and incredibly modest when they see the app I helped to create. If I tried to do that today, I would only embarrass myself because the hall of fame has still not been posted, and ~~my~~ the site's insecurity would be exposed. 

Given that it has been 8 or so weeks (2-4 sprints) since the class has concluded, it seems reasonable to expect the engineering team behind this project to have completed this feature by now. I have made a lot of promises to outside parties about being in this hall of fame, and people are starting to think that I am lying. I have staked my reputation on this, and if it is not up soon I may be forced to pay back my PPP loans which I had intended to have forgiven upon receiving this accolade. My livelihood is at stake; I do not want to have to pay the salaries for my employees out of my business's own pockets. Thank you for understanding.

Steps to reproduce:
1. Bake muffins for the entire CS 480 Spring class
2. Visit [the CS 492 Hall of Fame](https://web.engr.oregonstate.edu/~hessro/teaching/hof/cs492)
3. Observe that the only set of entries is for Winter 2022

**Comment by robwhess** [comment]
@ElijahCirioli I'm not able to perform step 1 in my development environment, but I think I was still able to fix this issue in PR #30.  I'd be interested in getting your eyes on that PR.  @Nyumat, I'd be interested in your thoughts, as well.

**Comment by robwhess** [comment]
Also, sorry about the delay on this, @ElijahCirioli.  We've only got a 1-person engineering team here at MyOSUWebsite, and we've been a little preoccupied recently meeting release deadlines for other products.

**Comment by gnubufferoverflows** [comment]
Hi Rob,

In your previous message, it says that MyOSUWebsite only has a 1-person engineering team. Does the staff of MyOSUWebsite also include feline employees?

**Comment by robwhess** [comment]
> Hi Rob,
> 
> In your previous message, it says that MyOSUWebsite only has a 1-person engineering team. Does the staff of MyOSUWebsite also include feline employees?

@robert0004 The feline workers are technically unpaid interns.
